# Generated by Django 2.2.6 on 2019-10-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemquarto',
            name='url',
            field=models.ImageField(upload_to='imagem'),
        ),
    ]
