# Generated by Django 2.2.6 on 2019-10-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarto', '0002_auto_20191004_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemquarto',
            name='url',
            field=models.ImageField(upload_to='quarto_imagens'),
        ),
    ]
